### ISSUE TITLE
[功能] 演示站点样式未适配暗黑模式

### ISSUE THREAD

**Issue by sangyuxiaowu** [AchievedOwner/TDesignBlazor#188]
#### 详细描述

控制台执行后，组件因设置有可以适配，但是演示站点的自定义样式没有实现暗黑模式
```html
document.documentElement.setAttribute('theme-mode', 'dark');
```

**Comment by sangyuxiaowu** [comment]
我来搞搞看

**Comment by sangyuxiaowu** [comment]
我看到有TDesignOptions.cs 但是似乎不是给全局暗黑模式用的。doc 文档并没有实现 TDesign-doc-tabs ，当然也是没有 TDesign-theme-tabs 的。全局暗黑模式这一块的设计是要在 TDesign.Docs.Shared 还是在类库中呢？

**Comment by AchievedOwner** [comment]
我理解这块代码应该是需要用 JS 来实现切换

**Comment by sangyuxiaowu** [comment]
> 我理解这块代码应该是需要用 JS 来实现切换

那行，就先不管和原站点样式的问题了，任务主要是补充文档相关的暗黑css，组件的暗黑效果因为css都有适配，基本没什么问题

**Comment by AchievedOwner** [comment]
> 我看到有TDesignOptions.cs 但是似乎不是给全局暗黑模式用的。doc 文档并没有实现 TDesign-doc-tabs ，当然也是没有 TDesign-theme-tabs 的。全局暗黑模式这一块的设计是要在 TDesign.Docs.Shared 还是在类库中呢？

当初设计了这个参数，目前只有 Menu 组件中使用了
