### ISSUE TITLE
[缺陷]

### ISSUE THREAD

**Issue by ydwpython** [AchievedOwner/TDesignBlazor#190]
#### 详细描述

首页介绍link     css 写错了

`<link rel=""stylesheet"" href=""_content/TDesign/tdesign-blazor.css"" />`

#### 重现步骤
1. ...
2. ...
3. ...
4. ...

#### 期望结果

 `<link rel="" stylesheet"" href="_content /TDesign/tdesign-blazor.css" />`

#### 托管方式
- [ ] Blazor Server
- [ ] Blazor WebAssembly

#### 浏览器版本
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] 其他

#### 备注
是否还有其他的关于该问题的补充内容

**Comment by AchievedOwner** [comment]
还可以补充一个 `<script src="_content/TDesign/tdesign-blazor.js"></script>` 这个链接
