### ISSUE TITLE
[缺陷] 0.3 版本预览站点样式异常

### ISSUE THREAD

**Issue by sangyuxiaowu** [AchievedOwner/TDesignBlazor#207]
#### 详细描述

较上一版本，预览站点 css 样式存在较多问题：
1. 文字内容和div没有安全边界
2. 左右异常留白和突兀的方块像素
![image](https://user-images.githubusercontent.com/17669599/208940237-94e67701-e756-4994-afe1-0cef20a19b73.png)

3. 代码和示例区域区分不明显
![image](https://user-images.githubusercontent.com/17669599/208940411-e2b7592d-c750-4220-a284-d2544d6582f3.png)

#### 期望结果

修复样式问题

#### 托管方式
- [x] Blazor Server
- [x] Blazor WebAssembly

#### 浏览器版本
- [x] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] 其他

**Comment by AchievedOwner** [comment]
我也看到这块很奇怪的问题，而且报了一个 IO 的错误，还没有查明原因

**Comment by AchievedOwner** [comment]
![image](https://user-images.githubusercontent.com/52902266/209497678-fa3c96a2-9d2d-4e94-a51f-650d811e12eb.png)
已经查明原因，是因为 WebAssembly 项目无法获得项目的 xml 造成的，主要原因是 `ComponentAPI` 使用反射的问题
@wuxinheng
