### ISSUE TITLE
[功能] 为了代码高亮作出的妥协寻求合适的解决方案

### ISSUE THREAD

**Issue by sangyuxiaowu** [AchievedOwner/TDesignBlazor#215]
#### 详细描述

取消诸如 ：
为了代码高亮，在代码预览中去掉了 @变量 中的 @ 字符，例如 @bind-Value @ref ...，将显示为 bind-Value ref ...

寻求其他解决方案。因为这个对初学者非常不友好。也像是项目的一直存在的一个症结。

也许可以通过前端处理

https://github.com/highlightjs/highlightjs-cshtml-razor

**Comment by AchievedOwner** [comment]
我用的是 Markdig 这个包，不知道能不能兼容

**Comment by AchievedOwner** [comment]
> #### 详细描述
> 取消诸如 ： 为了代码高亮，在代码预览中去掉了 @变量 中的 @ 字符，例如 @bind-Value @ref ...，将显示为 bind-Value ref ...
> 
> 寻求其他解决方案。因为这个对初学者非常不友好。也像是项目的一直存在的一个症结。
> 
> 也许可以通过前端处理
> 
> https://github.com/highlightjs/highlightjs-cshtml-razor

期望你可以尝试解决这个问题

**Comment by sangyuxiaowu** [comment]
因为是说明文档类，网站几乎每页都在使用高亮，我计划在 _Layout.cshtml 和 index.html 直接引用和放置全局的 highlight.min.js ，是否合适？ @AchievedOwner
