### ISSUE TITLE
[缺陷] LayoutContent TAnchor 固定定位 修改为 TAffix 没有效果

### ISSUE THREAD

**Issue by wuxinheng** [AchievedOwner/TDesignBlazor#219]
#### 详细描述
LayoutContent TAnchor 固定定位 修改为 TAffix 没有效果

#### 重现步骤
1. LayoutContent TAnchor 固定定位 修改为 TAffix

#### 期望结果
页面锚点应固定

#### 托管方式
- [x] Blazor Server
- [ ] Blazor WebAssembly

#### 浏览器版本
- [x] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] 其他

#### 备注
**代码位置：**
![屏幕截图 2023-01-06 170938](https://user-images.githubusercontent.com/49859025/210969279-dd140cf2-eaf4-4e1e-8502-8a4e587acb7f.jpg)

**期望情况：**
![屏幕截图 2023-01-06 171451](https://user-images.githubusercontent.com/49859025/210969742-32d0fe14-cb9d-41b2-b4af-e7a8f2c8e981.jpg)

**实际情况：**
![屏幕截图 2023-01-06 171304](https://user-images.githubusercontent.com/49859025/210969435-1d2462f6-41ba-4618-a25d-85eee630e854.jpg)

**Comment by elvismile** [comment]
因使用方式不正确和js错误导致，js时间错误已在其他issue修复；
