### ISSUE TITLE
[缺陷] 组件的属性未生效

### ISSUE THREAD

**Issue by sangyuxiaowu** [AchievedOwner/TDesignBlazor#239]
#### 详细描述

演示站点有 `AdditionalStyle` 添加了 `position: fixed` 其未生效。表现形式不对。

https://github.com/AchievedOwner/TDesignBlazor/blob/ba5df91d4db2c398d1ab5fd01829a4501595238a/doc/TDesign.Docs.Shared/Layouts/LayoutContent.razor#L7

#### 重现步骤

演示站点 http://tblazor.com/components/menu

![image](https://user-images.githubusercontent.com/17669599/220149973-7c023777-0a44-46d7-ba1b-b674a9443422.png)

#### 期望结果

修复 AdditionalStyle 未生效，优化用户阅读文档体验。

#### 托管方式
- [x] Blazor Server
- [x] Blazor WebAssembly

#### 浏览器版本
- [x] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] 其他

**Comment by AchievedOwner** [comment]
当前组件未实现 `IAdditionalStyle` 接口，则不支持该字段，因此可使用 `style` 来赋值
