### ISSUE TITLE
[招募]期待有志之士可以让项目继续发光发热

### ISSUE THREAD

**Issue by AchievedOwner** [AchievedOwner/TDesignBlazor#271]
由于本人的工作生活出现了不可预见的问题，现在暂时没有多余的精力来继续投入到这个项目中，希望有志之士可以承接这个项目，让这个项目持续发光发热。

转移方案可以有以下方式：
1. 项目归属直接转移到有志之士的账号
2. 项目归档，有志之士提供新的仓库链接 
3. 其他方案请留言

期待有志之士留下姓名

**PS：本人会持续承担服务器和域名的费用**

**Comment by sangyuxiaowu** [comment]
唉，保重身体！劳逸结合，我明天就开始休假了
